# Logger configuration
---

version: 1
disable_existing_loggers: false
formatters:
  console:
    format: '%(asctime)s UTC [%(process)d] %(levelname)-7s %(name)s:%(lineno)s %(message)s'
  console_colour:
    class: colorlog.ColoredFormatter
    format: '%(log_color)s%(asctime)s UTC [%(process)d] %(levelname)-7s %(name)s:%(lineno)s%(reset)s %(message)s'
  brief:
    format: '%(levelname)-7s [%(process)d] %(message)s'
  debug:
    format: '%(asctime)s UTC [%(process)d] %(levelname)-7s %(name)s:%(lineno)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: console
    stream: ext://sys.stdout
  console_colour:
    class: logging.StreamHandler
    level: INFO
    formatter: console_colour
    stream: ext://sys.stdout
  simple_log_file:
    class: logging.FileHandler
    level: INFO
    formatter: brief
    filename: main_log.txt
    mode: w
  debug_log_file:
    class: logging.FileHandler
    level: DEBUG
    formatter: debug
    filename: main_log_debug.txt
    mode: w
root:
  level: DEBUG
#   handlers: [console, simple_log_file, debug_log_file]
  handlers: [console_colour, simple_log_file, debug_log_file]
